# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
